---
database:
  # Auth info - Admin user which has permissions to restore DB
  auth:
    login_host: postgres
    login_port: 5432
    login_db: defaultdb
    login_user: admin_user
    login_password: "strong_password_here"

s3:
  endpoint_url: https://minio.lab.incubateur.finances.rie.gouv.fr
  alias_name: s3_tmp_alias
  access_key: 
  secret_key: 
  bucket: 
  key: 

filesystem:
  # Temporary path to store downloaded backups
  tmp_path: /tmp/postgres_backups
