k8s:
  namespace:

helm:
  # check official links (https://airflow.apache.org/docs/helm-chart/stable/index.html)
  repo_name: apache-airflow
  repo_url: https://airflow.apache.org
  chart_name: airflow
  release_name:

values_files:
  # Path where jinja template is rendered
  tmp_path: /tmp/airflow_values.yaml

  # SAVE THOSE VALUES
  fernetKey:
  webserverSecretKey:  # Airflow 2+
  apiSecretKey: # Airflow 3+
  jwtSecret: # Airflow 3+

  env_vars:
    # Logging
    - name: "AIRFLOW__LOGGING__REMOTE_LOGGING"
      value: False
    - name: "AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID"
      value:
    - name: "AIRFLOW__LOGGING__DELETE_LOCAL_LOGS"
      value:  False
    - name: "AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER"
      value:
    # SMTP
    - name: "AIRFLOW__SMTP__SMTP_HOST"
      value: ""
    - name: "AIRFLOW__SMTP__SMTP_PORT"
      value: "123"
    - name: "AIRFLOW__SMTP__SMTP_MAIL_FROM"
      value: ""
    - name: "AIRFLOW__SMTP__SMTP_STARTTLS"
      value: "false"
    - name: "AIRFLOW__SMTP__SMTP_SSL"
      value: "false"
    # Apache polaris x MinIO - Nubonyxia context
    - name: "SSL_CERT_FILE"
      value: "/usr/local/share/ca-certificates/customCA.crt"
    - name: "REQUESTS_CA_BUNDLE"
      value: "/usr/local/share/ca-certificates/customCA.crt"
    - name: "AWS_CA_BUNDLE"
      value: "/usr/local/share/ca-certificates/customCA.crt"
    - name: "CURL_CA_BUNDLE"
      value: "/usr/local/share/ca-certificates/customCA.crt"
    - name: "AWS_ACCESS_KEY_ID"
      value:
    - name: "AWS_SECRET_ACCESS_KEY"
      value:

  # Ingress configuration - Airflow 3+
  ingress:
    # Configs for the Ingress of the API Server
    apiServer:
      # Enable API Server ingress resource
      enabled: true
      # The hostnames or hosts configuration for the web Ingress
      hosts:
        # The hostname for the web Ingress (templated)
        - name: custom.lab.incubateur.finances.rie.gouv.fr

    # Configs for the Ingress of the web Service - Airflow < 3
    web:
      # Enable web ingress resource
      enabled: false

      # The hostnames or hosts configuration for the web Ingress
      hosts:
        # The hostname for the web Ingress (templated)
        - name: custom.lab.incubateur.finances.rie.gouv.fr

  # Airflow database & redis config
  data:
    # Otherwise pass connection values in
    metadataConnection:
      user:
      pass:
      protocol: postgresql
      host:
      port: 5432
      db:

  # Airflow webserver settings
  webserver:
    enabled: true
    # Create initial user.
    defaultUser:
      enabled: true
      role: Admin
      username:
      email:
      firstName:
      lastName:
      password:

  # Git sync
  dags:
    gitSync:
      enabled: true
      repo: your_repo_https_link
      branch: main
      rev: HEAD
      ref: main
      depth: 1
      maxFailures: 1
      # subPath:
      period: 20s
